theme: jekyll-theme-slate
title: "Ripeer's homepage"
description: "Bookmark this to keep an eye on my project updates!"

# Configuration personnalisée pour la navigation
nav:
  - title: "Présentation"
    url: "/presentation.html"
  - title: "Versions"
    url: "/versions.html"
